apiVersion: v1
appVersion: 2.3.2
description: A feature-rich flexible e-commerce solution. It includes transaction
  options, multi-store functionality, loyalty programs, product categorization and
  shopper filtering, promotion rules, and more.
engine: gotpl
home: https://magento.com/
icon: https://bitnami.com/assets/stacks/magento/img/magento-stack-110x117.png
keywords:
- magento
- e-commerce
- http
- web
- php
maintainers:
- email: darrius@blue360media.com
  name: Blue360media.com
name: magento blue360media.com
sources:
- https://github.com/DarriusAlexander/blue360media-docker
version: latest
